package gpu

import (
	"testing"
	"unsafe"
)

// The numbers on the right were printed by a C program compiled against wgpu-native
// v29.0.0.0's webgpu.h and wgpu.h (sizeof, offsetof, the enum values) on x86-64 Linux.
// Windows x64 and arm64 lay these structs out the same way: no bit fields, no long.

var layouts = []struct {
	name   string
	got, c uintptr
}{
	{"stringView", unsafe.Sizeof(stringView{}), 16},
	{"stringView.length", unsafe.Offsetof(stringView{}.length), 8},
	{"chainedStruct", unsafe.Sizeof(chainedStruct{}), 16},
	{"chainedStruct.sType", unsafe.Offsetof(chainedStruct{}.sType), 8},
	{"wExtent3D", unsafe.Sizeof(wExtent3D{}), 12},
	{"wOrigin3D", unsafe.Sizeof(wOrigin3D{}), 12},
	{"wColor", unsafe.Sizeof(wColor{}), 32},
	{"wInstanceDescriptor", unsafe.Sizeof(wInstanceDescriptor{}), 32},
	{"wInstanceDescriptor.requiredFeatureCount", unsafe.Offsetof(wInstanceDescriptor{}.requiredFeatureCount), 8},
	{"wInstanceDescriptor.requiredFeatures", unsafe.Offsetof(wInstanceDescriptor{}.requiredFeatures), 16},
	{"wInstanceDescriptor.requiredLimits", unsafe.Offsetof(wInstanceDescriptor{}.requiredLimits), 24},
	{"wInstanceExtras", unsafe.Sizeof(wInstanceExtras{}), 112},
	{"wInstanceExtras.backends", unsafe.Offsetof(wInstanceExtras{}.backends), 16},
	{"wInstanceExtras.flags", unsafe.Offsetof(wInstanceExtras{}.flags), 24},
	{"wInstanceExtras.dx12ShaderCompiler", unsafe.Offsetof(wInstanceExtras{}.dx12ShaderCompiler), 32},
	{"wInstanceExtras.gles3MinorVersion", unsafe.Offsetof(wInstanceExtras{}.gles3MinorVersion), 36},
	{"wInstanceExtras.glFenceBehaviour", unsafe.Offsetof(wInstanceExtras{}.glFenceBehaviour), 40},
	{"wInstanceExtras.dxcPath", unsafe.Offsetof(wInstanceExtras{}.dxcPath), 48},
	{"wInstanceExtras.dxcMaxShaderModel", unsafe.Offsetof(wInstanceExtras{}.dxcMaxShaderModel), 64},
	{"wInstanceExtras.dx12PresentationSystem", unsafe.Offsetof(wInstanceExtras{}.dx12PresentationSystem), 68},
	{"wInstanceExtras.budgetForDeviceCreation", unsafe.Offsetof(wInstanceExtras{}.budgetForDeviceCreation), 72},
	{"wInstanceExtras.budgetForDeviceLoss", unsafe.Offsetof(wInstanceExtras{}.budgetForDeviceLoss), 80},
	{"wRequestAdapterOptions", unsafe.Sizeof(wRequestAdapterOptions{}), 32},
	{"wRequestAdapterOptions.featureLevel", unsafe.Offsetof(wRequestAdapterOptions{}.featureLevel), 8},
	{"wRequestAdapterOptions.powerPreference", unsafe.Offsetof(wRequestAdapterOptions{}.powerPreference), 12},
	{"wRequestAdapterOptions.forceFallbackAdapter", unsafe.Offsetof(wRequestAdapterOptions{}.forceFallbackAdapter), 16},
	{"wRequestAdapterOptions.backendType", unsafe.Offsetof(wRequestAdapterOptions{}.backendType), 20},
	{"wRequestAdapterOptions.compatibleSurface", unsafe.Offsetof(wRequestAdapterOptions{}.compatibleSurface), 24},
	{"wCallbackInfo", unsafe.Sizeof(wCallbackInfo{}), 40},
	{"wCallbackInfo.mode", unsafe.Offsetof(wCallbackInfo{}.mode), 8},
	{"wCallbackInfo.callback", unsafe.Offsetof(wCallbackInfo{}.callback), 16},
	{"wCallbackInfo.userdata1", unsafe.Offsetof(wCallbackInfo{}.userdata1), 24},
	{"wCallbackInfo.userdata2", unsafe.Offsetof(wCallbackInfo{}.userdata2), 32},
	{"wCallbackInfo", unsafe.Sizeof(wCallbackInfo{}), 40},
	{"wCallbackInfo.userdata1", unsafe.Offsetof(wCallbackInfo{}.userdata1), 24},
	{"wCallbackInfo", unsafe.Sizeof(wCallbackInfo{}), 40},
	{"wCallbackInfo.userdata1", unsafe.Offsetof(wCallbackInfo{}.userdata1), 24},
	{"wCallbackInfo", unsafe.Sizeof(wCallbackInfo{}), 40},
	{"wCallbackInfo.userdata1", unsafe.Offsetof(wCallbackInfo{}.userdata1), 24},
	{"wCallbackInfo", unsafe.Sizeof(wCallbackInfo{}), 40},
	{"wCallbackInfo.userdata1", unsafe.Offsetof(wCallbackInfo{}.userdata1), 24},
	{"wUncapturedErrorCallbackInfo", unsafe.Sizeof(wUncapturedErrorCallbackInfo{}), 32},
	{"wUncapturedErrorCallbackInfo.callback", unsafe.Offsetof(wUncapturedErrorCallbackInfo{}.callback), 8},
	{"wUncapturedErrorCallbackInfo.userdata1", unsafe.Offsetof(wUncapturedErrorCallbackInfo{}.userdata1), 16},
	{"wUncapturedErrorCallbackInfo.userdata2", unsafe.Offsetof(wUncapturedErrorCallbackInfo{}.userdata2), 24},
	{"wQueueDescriptor", unsafe.Sizeof(wQueueDescriptor{}), 24},
	{"wQueueDescriptor.label", unsafe.Offsetof(wQueueDescriptor{}.label), 8},
	{"wDeviceDescriptor", unsafe.Sizeof(wDeviceDescriptor{}), 144},
	{"wDeviceDescriptor.label", unsafe.Offsetof(wDeviceDescriptor{}.label), 8},
	{"wDeviceDescriptor.requiredFeatureCount", unsafe.Offsetof(wDeviceDescriptor{}.requiredFeatureCount), 24},
	{"wDeviceDescriptor.requiredFeatures", unsafe.Offsetof(wDeviceDescriptor{}.requiredFeatures), 32},
	{"wDeviceDescriptor.requiredLimits", unsafe.Offsetof(wDeviceDescriptor{}.requiredLimits), 40},
	{"wDeviceDescriptor.defaultQueue", unsafe.Offsetof(wDeviceDescriptor{}.defaultQueue), 48},
	{"wDeviceDescriptor.deviceLostCallbackInfo", unsafe.Offsetof(wDeviceDescriptor{}.deviceLostCallbackInfo), 72},
	{"wDeviceDescriptor.uncapturedErrorCallbackInfo", unsafe.Offsetof(wDeviceDescriptor{}.uncapturedErrorCallbackInfo), 112},
	{"wShaderSourceWGSL", unsafe.Sizeof(wShaderSourceWGSL{}), 32},
	{"wShaderSourceWGSL.code", unsafe.Offsetof(wShaderSourceWGSL{}.code), 16},
	{"wShaderModuleDescriptor", unsafe.Sizeof(wShaderModuleDescriptor{}), 24},
	{"wShaderModuleDescriptor.label", unsafe.Offsetof(wShaderModuleDescriptor{}.label), 8},
	{"wBufferBindingLayout", unsafe.Sizeof(wBufferBindingLayout{}), 24},
	{"wBufferBindingLayout.typ", unsafe.Offsetof(wBufferBindingLayout{}.typ), 8},
	{"wBufferBindingLayout.hasDynamicOffset", unsafe.Offsetof(wBufferBindingLayout{}.hasDynamicOffset), 12},
	{"wBufferBindingLayout.minBindingSize", unsafe.Offsetof(wBufferBindingLayout{}.minBindingSize), 16},
	{"wSamplerBindingLayout", unsafe.Sizeof(wSamplerBindingLayout{}), 16},
	{"wSamplerBindingLayout.typ", unsafe.Offsetof(wSamplerBindingLayout{}.typ), 8},
	{"wTextureBindingLayout", unsafe.Sizeof(wTextureBindingLayout{}), 24},
	{"wTextureBindingLayout.sampleType", unsafe.Offsetof(wTextureBindingLayout{}.sampleType), 8},
	{"wTextureBindingLayout.viewDimension", unsafe.Offsetof(wTextureBindingLayout{}.viewDimension), 12},
	{"wTextureBindingLayout.multisampled", unsafe.Offsetof(wTextureBindingLayout{}.multisampled), 16},
	{"wStorageTextureBindingLayout", unsafe.Sizeof(wStorageTextureBindingLayout{}), 24},
	{"wStorageTextureBindingLayout.access", unsafe.Offsetof(wStorageTextureBindingLayout{}.access), 8},
	{"wStorageTextureBindingLayout.format", unsafe.Offsetof(wStorageTextureBindingLayout{}.format), 12},
	{"wStorageTextureBindingLayout.viewDimension", unsafe.Offsetof(wStorageTextureBindingLayout{}.viewDimension), 16},
	{"wBindGroupLayoutEntry", unsafe.Sizeof(wBindGroupLayoutEntry{}), 120},
	{"wBindGroupLayoutEntry.binding", unsafe.Offsetof(wBindGroupLayoutEntry{}.binding), 8},
	{"wBindGroupLayoutEntry.visibility", unsafe.Offsetof(wBindGroupLayoutEntry{}.visibility), 16},
	{"wBindGroupLayoutEntry.bindingArraySize", unsafe.Offsetof(wBindGroupLayoutEntry{}.bindingArraySize), 24},
	{"wBindGroupLayoutEntry.buffer", unsafe.Offsetof(wBindGroupLayoutEntry{}.buffer), 32},
	{"wBindGroupLayoutEntry.sampler", unsafe.Offsetof(wBindGroupLayoutEntry{}.sampler), 56},
	{"wBindGroupLayoutEntry.texture", unsafe.Offsetof(wBindGroupLayoutEntry{}.texture), 72},
	{"wBindGroupLayoutEntry.storageTexture", unsafe.Offsetof(wBindGroupLayoutEntry{}.storageTexture), 96},
	{"wBindGroupLayoutDescriptor", unsafe.Sizeof(wBindGroupLayoutDescriptor{}), 40},
	{"wBindGroupLayoutDescriptor.label", unsafe.Offsetof(wBindGroupLayoutDescriptor{}.label), 8},
	{"wBindGroupLayoutDescriptor.entryCount", unsafe.Offsetof(wBindGroupLayoutDescriptor{}.entryCount), 24},
	{"wBindGroupLayoutDescriptor.entries", unsafe.Offsetof(wBindGroupLayoutDescriptor{}.entries), 32},
	{"wBindGroupEntry", unsafe.Sizeof(wBindGroupEntry{}), 56},
	{"wBindGroupEntry.binding", unsafe.Offsetof(wBindGroupEntry{}.binding), 8},
	{"wBindGroupEntry.buffer", unsafe.Offsetof(wBindGroupEntry{}.buffer), 16},
	{"wBindGroupEntry.offset", unsafe.Offsetof(wBindGroupEntry{}.offset), 24},
	{"wBindGroupEntry.size", unsafe.Offsetof(wBindGroupEntry{}.size), 32},
	{"wBindGroupEntry.sampler", unsafe.Offsetof(wBindGroupEntry{}.sampler), 40},
	{"wBindGroupEntry.textureView", unsafe.Offsetof(wBindGroupEntry{}.textureView), 48},
	{"wBindGroupDescriptor", unsafe.Sizeof(wBindGroupDescriptor{}), 48},
	{"wBindGroupDescriptor.label", unsafe.Offsetof(wBindGroupDescriptor{}.label), 8},
	{"wBindGroupDescriptor.layout", unsafe.Offsetof(wBindGroupDescriptor{}.layout), 24},
	{"wBindGroupDescriptor.entryCount", unsafe.Offsetof(wBindGroupDescriptor{}.entryCount), 32},
	{"wBindGroupDescriptor.entries", unsafe.Offsetof(wBindGroupDescriptor{}.entries), 40},
	{"wPipelineLayoutDescriptor", unsafe.Sizeof(wPipelineLayoutDescriptor{}), 48},
	{"wPipelineLayoutDescriptor.label", unsafe.Offsetof(wPipelineLayoutDescriptor{}.label), 8},
	{"wPipelineLayoutDescriptor.bindGroupLayoutCount", unsafe.Offsetof(wPipelineLayoutDescriptor{}.bindGroupLayoutCount), 24},
	{"wPipelineLayoutDescriptor.bindGroupLayouts", unsafe.Offsetof(wPipelineLayoutDescriptor{}.bindGroupLayouts), 32},
	{"wPipelineLayoutDescriptor.immediateSize", unsafe.Offsetof(wPipelineLayoutDescriptor{}.immediateSize), 40},
	{"wVertexAttribute", unsafe.Sizeof(wVertexAttribute{}), 32},
	{"wVertexAttribute.format", unsafe.Offsetof(wVertexAttribute{}.format), 8},
	{"wVertexAttribute.offset", unsafe.Offsetof(wVertexAttribute{}.offset), 16},
	{"wVertexAttribute.shaderLocation", unsafe.Offsetof(wVertexAttribute{}.shaderLocation), 24},
	{"wVertexBufferLayout", unsafe.Sizeof(wVertexBufferLayout{}), 40},
	{"wVertexBufferLayout.stepMode", unsafe.Offsetof(wVertexBufferLayout{}.stepMode), 8},
	{"wVertexBufferLayout.arrayStride", unsafe.Offsetof(wVertexBufferLayout{}.arrayStride), 16},
	{"wVertexBufferLayout.attributeCount", unsafe.Offsetof(wVertexBufferLayout{}.attributeCount), 24},
	{"wVertexBufferLayout.attributes", unsafe.Offsetof(wVertexBufferLayout{}.attributes), 32},
	{"wVertexState", unsafe.Sizeof(wVertexState{}), 64},
	{"wVertexState.module", unsafe.Offsetof(wVertexState{}.module), 8},
	{"wVertexState.entryPoint", unsafe.Offsetof(wVertexState{}.entryPoint), 16},
	{"wVertexState.constantCount", unsafe.Offsetof(wVertexState{}.constantCount), 32},
	{"wVertexState.constants", unsafe.Offsetof(wVertexState{}.constants), 40},
	{"wVertexState.bufferCount", unsafe.Offsetof(wVertexState{}.bufferCount), 48},
	{"wVertexState.buffers", unsafe.Offsetof(wVertexState{}.buffers), 56},
	{"wBlendComponent", unsafe.Sizeof(wBlendComponent{}), 12},
	{"wBlendComponent.operation", unsafe.Offsetof(wBlendComponent{}.operation), 0},
	{"wBlendComponent.srcFactor", unsafe.Offsetof(wBlendComponent{}.srcFactor), 4},
	{"wBlendComponent.dstFactor", unsafe.Offsetof(wBlendComponent{}.dstFactor), 8},
	{"wBlendState", unsafe.Sizeof(wBlendState{}), 24},
	{"wBlendState.alpha", unsafe.Offsetof(wBlendState{}.alpha), 12},
	{"wColorTargetState", unsafe.Sizeof(wColorTargetState{}), 32},
	{"wColorTargetState.format", unsafe.Offsetof(wColorTargetState{}.format), 8},
	{"wColorTargetState.blend", unsafe.Offsetof(wColorTargetState{}.blend), 16},
	{"wColorTargetState.writeMask", unsafe.Offsetof(wColorTargetState{}.writeMask), 24},
	{"wFragmentState", unsafe.Sizeof(wFragmentState{}), 64},
	{"wFragmentState.module", unsafe.Offsetof(wFragmentState{}.module), 8},
	{"wFragmentState.entryPoint", unsafe.Offsetof(wFragmentState{}.entryPoint), 16},
	{"wFragmentState.constantCount", unsafe.Offsetof(wFragmentState{}.constantCount), 32},
	{"wFragmentState.constants", unsafe.Offsetof(wFragmentState{}.constants), 40},
	{"wFragmentState.targetCount", unsafe.Offsetof(wFragmentState{}.targetCount), 48},
	{"wFragmentState.targets", unsafe.Offsetof(wFragmentState{}.targets), 56},
	{"wPrimitiveState", unsafe.Sizeof(wPrimitiveState{}), 32},
	{"wPrimitiveState.topology", unsafe.Offsetof(wPrimitiveState{}.topology), 8},
	{"wPrimitiveState.stripIndexFormat", unsafe.Offsetof(wPrimitiveState{}.stripIndexFormat), 12},
	{"wPrimitiveState.frontFace", unsafe.Offsetof(wPrimitiveState{}.frontFace), 16},
	{"wPrimitiveState.cullMode", unsafe.Offsetof(wPrimitiveState{}.cullMode), 20},
	{"wPrimitiveState.unclippedDepth", unsafe.Offsetof(wPrimitiveState{}.unclippedDepth), 24},
	{"wStencilFaceState", unsafe.Sizeof(wStencilFaceState{}), 16},
	{"wStencilFaceState.compare", unsafe.Offsetof(wStencilFaceState{}.compare), 0},
	{"wStencilFaceState.failOp", unsafe.Offsetof(wStencilFaceState{}.failOp), 4},
	{"wStencilFaceState.depthFailOp", unsafe.Offsetof(wStencilFaceState{}.depthFailOp), 8},
	{"wStencilFaceState.passOp", unsafe.Offsetof(wStencilFaceState{}.passOp), 12},
	{"wDepthStencilState", unsafe.Sizeof(wDepthStencilState{}), 72},
	{"wDepthStencilState.format", unsafe.Offsetof(wDepthStencilState{}.format), 8},
	{"wDepthStencilState.depthWriteEnabled", unsafe.Offsetof(wDepthStencilState{}.depthWriteEnabled), 12},
	{"wDepthStencilState.depthCompare", unsafe.Offsetof(wDepthStencilState{}.depthCompare), 16},
	{"wDepthStencilState.stencilFront", unsafe.Offsetof(wDepthStencilState{}.stencilFront), 20},
	{"wDepthStencilState.stencilBack", unsafe.Offsetof(wDepthStencilState{}.stencilBack), 36},
	{"wDepthStencilState.stencilReadMask", unsafe.Offsetof(wDepthStencilState{}.stencilReadMask), 52},
	{"wDepthStencilState.stencilWriteMask", unsafe.Offsetof(wDepthStencilState{}.stencilWriteMask), 56},
	{"wDepthStencilState.depthBias", unsafe.Offsetof(wDepthStencilState{}.depthBias), 60},
	{"wDepthStencilState.depthBiasSlopeScale", unsafe.Offsetof(wDepthStencilState{}.depthBiasSlopeScale), 64},
	{"wDepthStencilState.depthBiasClamp", unsafe.Offsetof(wDepthStencilState{}.depthBiasClamp), 68},
	{"wMultisampleState", unsafe.Sizeof(wMultisampleState{}), 24},
	{"wMultisampleState.count", unsafe.Offsetof(wMultisampleState{}.count), 8},
	{"wMultisampleState.mask", unsafe.Offsetof(wMultisampleState{}.mask), 12},
	{"wMultisampleState.alphaToCoverageEnabled", unsafe.Offsetof(wMultisampleState{}.alphaToCoverageEnabled), 16},
	{"wRenderPipelineDescriptor", unsafe.Sizeof(wRenderPipelineDescriptor{}), 168},
	{"wRenderPipelineDescriptor.label", unsafe.Offsetof(wRenderPipelineDescriptor{}.label), 8},
	{"wRenderPipelineDescriptor.layout", unsafe.Offsetof(wRenderPipelineDescriptor{}.layout), 24},
	{"wRenderPipelineDescriptor.vertex", unsafe.Offsetof(wRenderPipelineDescriptor{}.vertex), 32},
	{"wRenderPipelineDescriptor.primitive", unsafe.Offsetof(wRenderPipelineDescriptor{}.primitive), 96},
	{"wRenderPipelineDescriptor.depthStencil", unsafe.Offsetof(wRenderPipelineDescriptor{}.depthStencil), 128},
	{"wRenderPipelineDescriptor.multisample", unsafe.Offsetof(wRenderPipelineDescriptor{}.multisample), 136},
	{"wRenderPipelineDescriptor.fragment", unsafe.Offsetof(wRenderPipelineDescriptor{}.fragment), 160},
	{"wSamplerDescriptor", unsafe.Sizeof(wSamplerDescriptor{}), 64},
	{"wSamplerDescriptor.label", unsafe.Offsetof(wSamplerDescriptor{}.label), 8},
	{"wSamplerDescriptor.addressModeU", unsafe.Offsetof(wSamplerDescriptor{}.addressModeU), 24},
	{"wSamplerDescriptor.addressModeV", unsafe.Offsetof(wSamplerDescriptor{}.addressModeV), 28},
	{"wSamplerDescriptor.addressModeW", unsafe.Offsetof(wSamplerDescriptor{}.addressModeW), 32},
	{"wSamplerDescriptor.magFilter", unsafe.Offsetof(wSamplerDescriptor{}.magFilter), 36},
	{"wSamplerDescriptor.minFilter", unsafe.Offsetof(wSamplerDescriptor{}.minFilter), 40},
	{"wSamplerDescriptor.mipmapFilter", unsafe.Offsetof(wSamplerDescriptor{}.mipmapFilter), 44},
	{"wSamplerDescriptor.lodMinClamp", unsafe.Offsetof(wSamplerDescriptor{}.lodMinClamp), 48},
	{"wSamplerDescriptor.lodMaxClamp", unsafe.Offsetof(wSamplerDescriptor{}.lodMaxClamp), 52},
	{"wSamplerDescriptor.compare", unsafe.Offsetof(wSamplerDescriptor{}.compare), 56},
	{"wSamplerDescriptor.maxAnisotropy", unsafe.Offsetof(wSamplerDescriptor{}.maxAnisotropy), 60},
	{"wBufferDescriptor", unsafe.Sizeof(wBufferDescriptor{}), 48},
	{"wBufferDescriptor.label", unsafe.Offsetof(wBufferDescriptor{}.label), 8},
	{"wBufferDescriptor.usage", unsafe.Offsetof(wBufferDescriptor{}.usage), 24},
	{"wBufferDescriptor.size", unsafe.Offsetof(wBufferDescriptor{}.size), 32},
	{"wBufferDescriptor.mappedAtCreation", unsafe.Offsetof(wBufferDescriptor{}.mappedAtCreation), 40},
	{"wTextureDescriptor", unsafe.Sizeof(wTextureDescriptor{}), 80},
	{"wTextureDescriptor.label", unsafe.Offsetof(wTextureDescriptor{}.label), 8},
	{"wTextureDescriptor.usage", unsafe.Offsetof(wTextureDescriptor{}.usage), 24},
	{"wTextureDescriptor.dimension", unsafe.Offsetof(wTextureDescriptor{}.dimension), 32},
	{"wTextureDescriptor.size", unsafe.Offsetof(wTextureDescriptor{}.size), 36},
	{"wTextureDescriptor.format", unsafe.Offsetof(wTextureDescriptor{}.format), 48},
	{"wTextureDescriptor.mipLevelCount", unsafe.Offsetof(wTextureDescriptor{}.mipLevelCount), 52},
	{"wTextureDescriptor.sampleCount", unsafe.Offsetof(wTextureDescriptor{}.sampleCount), 56},
	{"wTextureDescriptor.viewFormatCount", unsafe.Offsetof(wTextureDescriptor{}.viewFormatCount), 64},
	{"wTextureDescriptor.viewFormats", unsafe.Offsetof(wTextureDescriptor{}.viewFormats), 72},
	{"wCommandEncoderDescriptor", unsafe.Sizeof(wCommandEncoderDescriptor{}), 24},
	{"wCommandEncoderDescriptor.label", unsafe.Offsetof(wCommandEncoderDescriptor{}.label), 8},
	{"wCommandBufferDescriptor", unsafe.Sizeof(wCommandBufferDescriptor{}), 24},
	{"wCommandBufferDescriptor.label", unsafe.Offsetof(wCommandBufferDescriptor{}.label), 8},
	{"wRenderPassColorAttachment", unsafe.Sizeof(wRenderPassColorAttachment{}), 72},
	{"wRenderPassColorAttachment.view", unsafe.Offsetof(wRenderPassColorAttachment{}.view), 8},
	{"wRenderPassColorAttachment.depthSlice", unsafe.Offsetof(wRenderPassColorAttachment{}.depthSlice), 16},
	{"wRenderPassColorAttachment.resolveTarget", unsafe.Offsetof(wRenderPassColorAttachment{}.resolveTarget), 24},
	{"wRenderPassColorAttachment.loadOp", unsafe.Offsetof(wRenderPassColorAttachment{}.loadOp), 32},
	{"wRenderPassColorAttachment.storeOp", unsafe.Offsetof(wRenderPassColorAttachment{}.storeOp), 36},
	{"wRenderPassColorAttachment.clearValue", unsafe.Offsetof(wRenderPassColorAttachment{}.clearValue), 40},
	{"wRenderPassDepthStencilAttachment", unsafe.Sizeof(wRenderPassDepthStencilAttachment{}), 48},
	{"wRenderPassDepthStencilAttachment.view", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.view), 8},
	{"wRenderPassDepthStencilAttachment.depthLoadOp", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.depthLoadOp), 16},
	{"wRenderPassDepthStencilAttachment.depthStoreOp", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.depthStoreOp), 20},
	{"wRenderPassDepthStencilAttachment.depthClearValue", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.depthClearValue), 24},
	{"wRenderPassDepthStencilAttachment.depthReadOnly", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.depthReadOnly), 28},
	{"wRenderPassDepthStencilAttachment.stencilLoadOp", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.stencilLoadOp), 32},
	{"wRenderPassDepthStencilAttachment.stencilStoreOp", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.stencilStoreOp), 36},
	{"wRenderPassDepthStencilAttachment.stencilClearValue", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.stencilClearValue), 40},
	{"wRenderPassDepthStencilAttachment.stencilReadOnly", unsafe.Offsetof(wRenderPassDepthStencilAttachment{}.stencilReadOnly), 44},
	{"wRenderPassDescriptor", unsafe.Sizeof(wRenderPassDescriptor{}), 64},
	{"wRenderPassDescriptor.label", unsafe.Offsetof(wRenderPassDescriptor{}.label), 8},
	{"wRenderPassDescriptor.colorAttachmentCount", unsafe.Offsetof(wRenderPassDescriptor{}.colorAttachmentCount), 24},
	{"wRenderPassDescriptor.colorAttachments", unsafe.Offsetof(wRenderPassDescriptor{}.colorAttachments), 32},
	{"wRenderPassDescriptor.depthStencilAttachment", unsafe.Offsetof(wRenderPassDescriptor{}.depthStencilAttachment), 40},
	{"wRenderPassDescriptor.occlusionQuerySet", unsafe.Offsetof(wRenderPassDescriptor{}.occlusionQuerySet), 48},
	{"wRenderPassDescriptor.timestampWrites", unsafe.Offsetof(wRenderPassDescriptor{}.timestampWrites), 56},
	{"wTexelCopyTextureInfo", unsafe.Sizeof(wTexelCopyTextureInfo{}), 32},
	{"wTexelCopyTextureInfo.mipLevel", unsafe.Offsetof(wTexelCopyTextureInfo{}.mipLevel), 8},
	{"wTexelCopyTextureInfo.origin", unsafe.Offsetof(wTexelCopyTextureInfo{}.origin), 12},
	{"wTexelCopyTextureInfo.aspect", unsafe.Offsetof(wTexelCopyTextureInfo{}.aspect), 24},
	{"wTexelCopyBufferLayout", unsafe.Sizeof(wTexelCopyBufferLayout{}), 16},
	{"wTexelCopyBufferLayout.bytesPerRow", unsafe.Offsetof(wTexelCopyBufferLayout{}.bytesPerRow), 8},
	{"wTexelCopyBufferLayout.rowsPerImage", unsafe.Offsetof(wTexelCopyBufferLayout{}.rowsPerImage), 12},
	{"wTexelCopyBufferInfo", unsafe.Sizeof(wTexelCopyBufferInfo{}), 24},
	{"wTexelCopyBufferInfo.buffer", unsafe.Offsetof(wTexelCopyBufferInfo{}.buffer), 16},
	{"wAdapterInfo", unsafe.Sizeof(wAdapterInfo{}), 96},
	{"wAdapterInfo.vendor", unsafe.Offsetof(wAdapterInfo{}.vendor), 8},
	{"wAdapterInfo.architecture", unsafe.Offsetof(wAdapterInfo{}.architecture), 24},
	{"wAdapterInfo.device", unsafe.Offsetof(wAdapterInfo{}.device), 40},
	{"wAdapterInfo.description", unsafe.Offsetof(wAdapterInfo{}.description), 56},
	{"wAdapterInfo.backendType", unsafe.Offsetof(wAdapterInfo{}.backendType), 72},
	{"wAdapterInfo.adapterType", unsafe.Offsetof(wAdapterInfo{}.adapterType), 76},
	{"wAdapterInfo.vendorID", unsafe.Offsetof(wAdapterInfo{}.vendorID), 80},
	{"wAdapterInfo.deviceID", unsafe.Offsetof(wAdapterInfo{}.deviceID), 84},
	{"wAdapterInfo.subgroupMinSize", unsafe.Offsetof(wAdapterInfo{}.subgroupMinSize), 88},
	{"wAdapterInfo.subgroupMaxSize", unsafe.Offsetof(wAdapterInfo{}.subgroupMaxSize), 92},
}

var enums = []struct {
	name   string
	got, c uint64
}{
	{"FormatRGBA8Unorm", uint64(FormatRGBA8Unorm), 0x16},
	{"FormatRGBA8UnormSrgb", uint64(FormatRGBA8UnormSrgb), 0x17},
	{"FormatRGBA16Float", uint64(FormatRGBA16Float), 0x28},
	{"FormatDepth32Float", uint64(FormatDepth32Float), 0x30},
	{"TextureCopySrc", uint64(TextureCopySrc), 0x1},
	{"TextureCopyDst", uint64(TextureCopyDst), 0x2},
	{"TextureBinding", uint64(TextureBinding), 0x4},
	{"TextureRenderAttachmt", uint64(TextureRenderAttachmt), 0x10},
	{"BufferMapRead", uint64(BufferMapRead), 0x1},
	{"BufferCopySrc", uint64(BufferCopySrc), 0x4},
	{"BufferCopyDst", uint64(BufferCopyDst), 0x8},
	{"BufferIndex", uint64(BufferIndex), 0x10},
	{"BufferVertex", uint64(BufferVertex), 0x20},
	{"BufferUniform", uint64(BufferUniform), 0x40},
	{"StageVertex", uint64(StageVertex), 0x1},
	{"StageFragment", uint64(StageFragment), 0x2},
	{"SampleFloat", uint64(SampleFloat), 0x2},
	{"SampleDepth", uint64(SampleDepth), 0x4},
	{"IndexUint32", uint64(IndexUint32), 0x2},
	{"VertexFloat32x2", uint64(VertexFloat32x2), 0x1d},
	{"VertexFloat32x3", uint64(VertexFloat32x3), 0x1e},
	{"PointList", uint64(PointList), 0x1},
	{"TriangleList", uint64(TriangleList), 0x4},
	{"FrontCCW", uint64(FrontCCW), 0x1},
	{"CullNone", uint64(CullNone), 0x1},
	{"CullFront", uint64(CullFront), 0x2},
	{"CullBack", uint64(CullBack), 0x3},
	{"CompareLessEqual", uint64(CompareLessEqual), 0x4},
	{"BlendAdd", uint64(BlendAdd), 0x1},
	{"FactorOne", uint64(FactorOne), 0x2},
	{"FactorSrcAlpha", uint64(FactorSrcAlpha), 0x5},
	{"FactorOneMinusSrcAlpha", uint64(FactorOneMinusSrcAlpha), 0x6},
	{"FilterNearest", uint64(FilterNearest), 0x1},
	{"FilterLinear", uint64(FilterLinear), 0x2},
	{"ClampToEdge", uint64(ClampToEdge), 0x1},
	{"BackendD3D12", uint64(BackendD3D12), 0x4},
	{"BackendMetal", uint64(BackendMetal), 0x5},
	{"BackendVulkan", uint64(BackendVulkan), 0x6},
	{"BackendOpenGL", uint64(BackendOpenGL), 0x7},
	{"BackendOpenGLES", uint64(BackendOpenGLES), 0x8},
	{"AdapterCPU", uint64(AdapterCPU), 0x3},
	{"sTypeShaderSourceWGSL", uint64(sTypeShaderSourceWGSL), 0x2},
	{"sTypeInstanceExtras", uint64(sTypeInstanceExtras), 0x30006},
	{"instanceBackendVulkan", uint64(instanceBackendVulkan), 0x1},
	{"instanceBackendGL", uint64(instanceBackendGL), 0x2},
	{"instanceBackendDX12", uint64(instanceBackendDX12), 0x8},
	{"featureLevelCore", uint64(featureLevelCore), 0x2},
	{"callbackAllowProcess", uint64(callbackAllowProcess), 0x2},
	{"callbackAllowSpontaneous", uint64(callbackAllowSpontaneous), 0x3},
	{"statusSuccess", uint64(statusSuccess), 0x1},
	{"statusSuccess", uint64(statusSuccess), 0x1},
	{"statusSuccess", uint64(statusSuccess), 0x1},
	{"statusSuccess", uint64(statusSuccess), 0x1},
	{"powerLowPower", uint64(powerLowPower), 0x1},
	{"errorFilterValidation", uint64(errorFilterValidation), 0x1},
	{"errorTypeNoError", uint64(errorTypeNoError), 0x1},
	{"mapModeRead", uint64(mapModeRead), 0x1},
	{"textureDimension2D", uint64(textureDimension2D), 0x2},
	{"bufferBindingUniform", uint64(bufferBindingUniform), 0x2},
	{"samplerBindingFilter", uint64(samplerBindingFilter), 0x2},
	{"textureViewDimension2D", uint64(textureViewDimension2D), 0x2},
	{"loadOpClear", uint64(loadOpClear), 0x2},
	{"storeOpStore", uint64(storeOpStore), 0x1},
	{"vertexStepModeVertex", uint64(vertexStepModeVertex), 0x1},
	{"optionalBoolFalse", uint64(optionalBoolFalse), 0x0},
	{"optionalBoolTrue", uint64(optionalBoolTrue), 0x1},
	{"stencilKeep", uint64(stencilKeep), 0x1},
	{"compareAlways", uint64(compareAlways), 0x8},
	{"colorWriteAll", uint64(colorWriteAll), 0xf},
	{"depthSliceUndefined", uint64(depthSliceUndefined), 0xffffffff},
	{"wholeSize", uint64(wholeSize), 0xffffffffffffffff},
	{"strlen", uint64(strlen), 0xffffffffffffffff},
	{"aspectAll", uint64(aspectAll), 0x1},
}

func TestWireLayouts(t *testing.T) {
	for _, l := range layouts {
		if l.got != l.c {
			t.Errorf("%s: Go %d, C %d", l.name, l.got, l.c)
		}
	}
}

func TestEnumValues(t *testing.T) {
	for _, e := range enums {
		if e.got != e.c {
			t.Errorf("%s: Go %#x, C %#x", e.name, e.got, e.c)
		}
	}
}
